
name: Release

on:
  push
    # tags:
    #   - '*.*.*'

jobs:
  # release-crates:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: publish package to crates
  #       run: |
  #         cargo package
  #         cargo publish --token ${{ secrets.CARGO_TOKEN }}
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/traverse_rs
          asset_name: traverse_rs-linux-amd64
          tag: ${{ steps.bump_version.outputs.new_tag }}
          overwrite: true
